#!/bin/sh
if [ "${1}" == "post" ]; then
  # サスペンド後にトラックポイントが認識されなくなる問題の回避策
  echo -n none > /sys/devices/platform/i8042/serio1/drvctl
  sleep 1
  echo -n reconnect > /sys/devices/platform/i8042/serio1/drvctl
  sleep 3
  # 中ボタン貼り付け無効
　xinput set-button-map "TPPS/2 Elan TrackPoint" 1 0 3 4 5 6 7

fi
